# Generated by Django 2.0.9 on 2020-01-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runnerapp', '0002_table_1_table_2_table_3_table_4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table_3',
            old_name='table_3_user',
            new_name='skill_own',
        ),
        migrations.AddField(
            model_name='table_1',
            name='malasong_location',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='比赛地点'),
        ),
        migrations.AddField(
            model_name='table_1',
            name='malasong_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='比赛名称'),
        ),
        migrations.AddField(
            model_name='table_1',
            name='malasong_overbook_time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='比赛关闭抽签时间'),
        ),
        migrations.AddField(
            model_name='table_1',
            name='malasong_startbook_time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='比赛开始抽签时间'),
        ),
        migrations.AddField(
            model_name='table_1',
            name='malasong_time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='比赛时间'),
        ),
        migrations.AddField(
            model_name='table_2',
            name='happy_race_overbook_time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='比赛停止预约时间'),
        ),
        migrations.AddField(
            model_name='table_2',
            name='happy_race_startbook_time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='比赛开始预约时间'),
        ),
        migrations.AddField(
            model_name='table_2',
            name='happy_race_time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='比赛时间'),
        ),
        migrations.AddField(
            model_name='table_2',
            name='happy_raceg_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='比赛名称'),
        ),
        migrations.AddField(
            model_name='table_2',
            name='malasong_location',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='比赛地点'),
        ),
        migrations.AddField(
            model_name='table_3',
            name='skill_brief',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='skill_brief'),
        ),
        migrations.AddField(
            model_name='table_3',
            name='skill_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='skill_title'),
        ),
        migrations.AlterField(
            model_name='table_4',
            name='table_4_content',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='名人事迹详述'),
        ),
        migrations.AlterField(
            model_name='table_4',
            name='table_4_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='名人事迹总结'),
        ),
        migrations.AlterField(
            model_name='table_4',
            name='table_4_user',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='名人名字'),
        ),
    ]
