# Generated by Django 2.0.9 on 2020-01-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runnerapp', '0003_auto_20200123_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table_3',
            old_name='time',
            new_name='skill_time',
        ),
        migrations.RenameField(
            model_name='table_4',
            old_name='table_4_title',
            new_name='runner_main_achievement',
        ),
        migrations.AddField(
            model_name='table_3',
            name='table_2_user',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='表三作者'),
        ),
        migrations.AddField(
            model_name='table_4',
            name='runner_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='名人名字'),
        ),
        migrations.AlterField(
            model_name='table_3',
            name='skill_own',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='内容提供作者'),
        ),
        migrations.AlterField(
            model_name='table_4',
            name='table_4_user',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='表四作者'),
        ),
    ]
