# Generated by Django 2.0.9 on 2020-01-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runnerapp', '0005_auto_20200123_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table_1',
            old_name='table_1_id',
            new_name='table_id',
        ),
        migrations.RenameField(
            model_name='table_2',
            old_name='table_2_id',
            new_name='table_id',
        ),
        migrations.RenameField(
            model_name='table_3',
            old_name='table_3_id',
            new_name='table_id',
        ),
        migrations.RenameField(
            model_name='table_4',
            old_name='table_4_id',
            new_name='table_id',
        ),
    ]
