# Generated by Django 2.0.9 on 2020-01-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runnerapp', '0006_auto_20200123_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_1',
            name='table_type',
            field=models.IntegerField(default='1', editable=False, verbose_name='表种类'),
        ),
        migrations.AddField(
            model_name='table_2',
            name='table_type',
            field=models.IntegerField(default='2', editable=False, verbose_name='表种类'),
        ),
        migrations.AddField(
            model_name='table_3',
            name='table_type',
            field=models.IntegerField(default='3', editable=False, verbose_name='表种类'),
        ),
        migrations.AddField(
            model_name='table_4',
            name='table_type',
            field=models.IntegerField(default='4', editable=False, verbose_name='表种类'),
        ),
    ]
