# Generated by Django 2.0.9 on 2020-01-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runnerapp', '0007_auto_20200123_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_3',
            name='table_3_title',
        ),
    ]
